OdeToFood/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

OdeToFood/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string Message { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Message = "Hello World!";
        }
    }
}

OdeToFood/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;
using System.Reflection.Metadata.Ecma335;

namespace OdeToFood.Pages.Restaurants
{
    public class DelModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        public Restaurant restaurant { get; set; }

        public DelModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {
            restaurant = restaurantData.getById(restaurantId);
            if (restaurant == null)
            {
                return RedirectToPage("./Not_Found");
            }
            return Page();
        }

        public IActionResult OnPost(int restaurantId)
        {
            var restaurant = restaurantData.Delete(restaurantId);

            if (restaurant == null)
            {
                return RedirectToPage("./Not_Found");
            }
            restaurantData.Commit();
            TempData["Message"] = $"{restaurant.Name} deleted";
            return RedirectToPage("./List");
        }
    }
}

OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class DetailModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public Restaurant restaurant { get; set; }
        public readonly IRestaurantData restaurantData;

        public DetailModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {
            restaurant = restaurantData.getById(restaurantId);

            if(restaurant == null)
            {
                return RedirectToPage("./Not_Found");
            }

            return Page();
        }
    }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public Restaurant restaurant { get; set; }
        public readonly IRestaurantData restaurantData;
        public IEnumerable<SelectListItem> Cuisines { get; set; }
        public IHtmlHelper helper { get; set; }

        public EditModel(IRestaurantData restaurantData, IHtmlHelper helper)
        {
            this.restaurantData = restaurantData;
            this.helper = helper;
        }


        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = helper.GetEnumSelectList<CuisineType>();
            if (restaurantId.HasValue)
            {
                restaurant = restaurantData.getById(restaurantId.Value);
            }
            else
            {
                restaurant = new Restaurant();
            }
            if(restaurant == null)
            {
                return RedirectToPage("./Not_Found");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
     
            if (!ModelState.IsValid)
            {
                Cuisines = helper.GetEnumSelectList<CuisineType>();
                return Page();
            }

            if(restaurant.Id == 0)
            {
                restaurantData.Add(restaurant);
            }
            if(restaurant.Id > 0)
            {
                restaurantData.Update(restaurant); 
            }
            restaurantData.Commit();
            TempData["Message"] = "Restaurant Saved!";
            return RedirectToPage("./Detail", new { restaurantId = restaurant.Id });
        }
    }
}

OdeToFood/Pages/Restaurants/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        public readonly IConfiguration config;
        private readonly IRestaurantData restaurantData;

        [BindProperty (SupportsGet = true)]
        public string searchTerm { get; set; }
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public string Configuration { get; set; }

        public ListModel(IConfiguration config, IRestaurantData restaurantData)
        {
            this.config = config;
            this.restaurantData = restaurantData;
        }

        public void OnGet()
        {
            Configuration = config["Message"];
            Restaurants = restaurantData.GetRestaurantByName(searchTerm);
        }
    }
}

OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;

namespace OdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        public readonly IRestaurantData restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        } 

        public IViewComponentResult Invoke()
        {
            var count = restaurantData.GetCount();
            return View(count);
        }

    }
}

OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@*@section footer{
    <div>@Model.Message</div>
    }*@

OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restaurantId}"
@model OdeToFood.Pages.Restaurants.DelModel
@{
}

    <h1>Delete!</h1>
    <div class="alert alert-danger">
        Are you sure you want to delete @Model.restaurant.Name?
    </div>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a asp-page="List" class="btn btn-default">Cancel</a>
    </form>

OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:int?}"
@model OdeToFood.Pages.Restaurants.DetailModel
@{

    ViewData["Title"] = "Detail";

}

<h2>@Model.restaurant.Name</h2>

<div>
    Id: @Model.restaurant.Id
</div>
<div>
    Location: @Model.restaurant.Location
</div>
<div>
    Cuisine: @Model.restaurant.Cuisine
</div>

@if(Model.Message != null)
{
    <div class="alert alert-info"> @Model.Message</div>
}

<a asp-page="./List" class="btn btn-default">All Restaurants</a>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page
@model OdeToFood.Pages.Restaurants.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Editing @Model.restaurant.Name</h1>

<form method="post">

    <input type="hidden" asp-for="restaurant.Id" />
    <div class="form-group">
        <label asp-for="restaurant.Name"></label>
        <input asp-for="restaurant.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="restaurant.Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="restaurant.Location"></label>
        <input asp-for="restaurant.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="restaurant.Location"></span>
    </div>

    <div class="form-group">
        <label asp-for="restaurant.Cuisine"></label>
<select class="form-control" asp-for="restaurant.Cuisine" asp-items="Model.Cuisines"></select>   
</div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>
@*
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}
*@

OdeToFood/Pages/Restaurants/List.cshtml
@page
@model OdeToFood.Pages.Restaurants.ListModel
@{
    ViewData["Title"] = "List";

}

<h1>Restaurants</h1>

<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" value="" name="searchTerm" />
            <span class="input-group-btn">
                <button class="btn btn-default">
                    <i class="glyphicon glyphicon-search"></i>
                </button>
            </span>
        </div>
    </div>
</form>

@foreach (var r in Model.Restaurants)
{
    <partial name="_Summary" model="r" />
}


    <a asp-page=".\Edit" class="btn btn-primary">Add New</a>

@*@section footer{
    <div>@Model.Configuration</div>
}
*@

OdeToFood/Pages/Restaurants/Not_Found.cshtml
@page
@{
    ViewData["Title"] = "Not_Found";
}

<h1>Restaurant not found</h1>
<a class="btn btn-primary" asp-page="./List">Return to all</a>

OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurant

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@Model.Name</h3>
    </div>
    <div class="panel-body">
        <span>Location: @Model.Location</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>
    <div class="panel-footer">
        <a class="btn btn-lg" asp-page="./Detail" asp-route-restaurantId="@Model.Id">
            <i class="glyphicon glyphicon-zoom-in"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Edit" asp-route-restaurantId="@Model.Id">
            <i class="glyphicon glyphicon-edit"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Detail" asp-route-restaurantId="@Model.Id">
            <i class="glyphicon glyphicon-zoom-in"></i>
        </a>
        <a class="btn btn-lg" asp-page="./Delete" asp-route-restaurantId="@Model.Id">
            <i class="glyphicon glyphicon-trash"></i>
        </a>
    </div>
</div>

OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int
<div class="well">
    There are @Model restaurants here. <a class="btn btn-default" asp-page="/Restaurants/List"> See them all</a>
</div>

OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OdeToFood.styles.css" asp-append-version="true" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            <vc:restaurant-count></vc:restaurant-count>
            @RenderSection("footer", required: false)
            &copy; 2023 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false);
</body>
</html>